# Task 1

In [22]:
import numpy as np
a = np.array([[1,6],[2,8],[3,11],[3,10],[1,7]])

In [23]:
mean_a = np.mean(a, axis = 0)

In [24]:
mean_a


array([2. , 8.4])

## Task 2

In [25]:
a_centered = a - mean_a

In [26]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

## Task 3

In [28]:
a_centered_sp = np.dot(a_centered,mean_a)

In [29]:
a_centered_sp


array([-22.16,  -3.36,  23.84,  15.44, -13.76])

In [30]:
np. divide (a_centered_sp, 4)

array([-5.54, -0.84,  5.96,  3.86, -3.44])